import os

Import('env')

penv = env.Clone()

src = [
    "client.c",
    "config.c",
    "encrypt.c",
    "mparray.c",
    "poly.c",
    "rand.c",
    "prg.c",
    "server.c",
    "serial.c",
    "share.c",
]

libs = [
  "msgpackc"
]

# Visual studio does not support variable-length arrays
penv.Append(CFLAGS = ['-Wvla'])

penv.Append(LIBS = libs)
penv.StaticLibrary("mprio", src)

